### ISSUE TITLE
World corruption with BloodMagic SentinentSpectre

### ISSUE THREAD

**Issue by ChrisCrisis** [Ipsis/Woot#100]
Was testing around with your mod in creative and put different mobs into the factory.
The SentinentSpectre caused a world corrupting crash so the world cant be reloaded at the moment.

CrashReport
http://pastebin.com/3WBJNCan

**Comment by Ipsis** [comment]
Right, I now know why it crashes.
BM is expecting the SentientSpecter to be holding something and tries to drop it. It is not expecting this specific mob to be holding nothing, which is the mob that I'm using.

Looks like it is a known bug in BM and has been fixed in the last hour. It apparently happens in other spawners as well.

https://github.com/WayofTime/BloodMagic/issues/920
https://github.com/WayofTime/BloodMagic/commit/e541ed67e90e29a06e11c8e588e127803d8bc6dc
