### ISSUE TITLE
not getting salvage level parts with woot mod(cyberware mod)

### ISSUE THREAD

**Issue by DeathOfTime** [Ipsis/Woot#113]
http://i.imgur.com/2PIQGmq.png
i was testing if woot obeys sub-types of mobs for later when i found that when it was working on cyber zombies all the drops it got were manufactured quality and not salvage quality. Not for sure what to do about that in my game. Not even sure where to report it. So letting both mod authors have a glance at it on there respective githubs. 

will try and edit in the links to both posts. I don't care for re-posting. I don't really know how else to do it though.

https://github.com/Flaxbeard/Cyberware/issues/55
https://github.com/Ipsis/Woot/issues/113

edit: the salvaged part that is in there was from before i tested. forgot to removed it. I got that off the zombie i set the woot mob prism with.

Edit:
woot-1.10.2-1.2.0.jar
cyberware-1.9.4-1.10.2-beta-0.2.3.jar
in the "Spilled Juice" pack on the AT launcher. pack version 0.2.3.1.C

**Comment by Ipsis** [comment]
This will very probably by down to Woot.
Most mod's mob drops work fine with no special handling, but sometimes that is just down to luck than anything else ;)
I'll investigate and see if I can come up with a reason as to why it is not working.
I highly doubt that the problem is with Cyberware.

**Comment by Ipsis** [comment]
1) I was not calling the event to let Cyberware do a special spawn when I'm learning drops.
2) With this added I now get drops that say "Can deconstruct or scan"

Don't know if that is an improvement or not, but it is still not working the correct way.
Woot learns mob drops from both player kills and in learning mode, from fake mob kills.

However from reading a bit about Cyberware, I'm tempted to blacklist the Cyberware zombies.
The mod seems to be based around combat with the mobs to progress and allowing them to be farmed via Woot would unfair to the mod author. Please feel free to correct me if I misunderstand how the mod works though,

**Comment by DeathOfTime** [comment]
not a clue. sounds right though. the server i am testing this on has a low view distance so actual mob spawns are tough to get. even when i am the only one on. will suck but seems the right path. thanks for looking into this and deciding on a course of action.

guess i will scrap my progress on that mod and start from where i was before woot. i been wanting a excuse to go hunting again anyways.

**Comment by RealGrep** [comment]
I was going to blacklist the Cyberware zombies anyway. And if someone doesn't like that, they're free to remove it in the config file, anyway. It's a good thing if it works correctly, of course, but I agree with default blacklisting.

**Comment by Ipsis** [comment]
This is not relevant to the discussion, but just a few notes for me as to why Cyberware didn't get the variety of drops that it should have, even after calling the special spawn code.

On special spawn,  the zombie will get shards, trenchcoat and jacket. However, the random cyberware is only added on the onLivingUpdate call, which Woot will not call. I cannot think of any safe way of calling that without potentially breaking something else.

That is why I was only ever seeing the base drops and why if someone removes blacklist from the config file, then they would still not see all the drops. From the Cyberware code, the call to addRandomCyberware IS in the constructor, but has been commented out.

Since Woot also learns from all kills, including manual kills, some loot would be learned over time.

**Comment by Ipsis** [comment]
6193e69eb56d201dc557bc0febbdee3f0e13be35
