### ISSUE TITLE
Self Termination

### ISSUE THREAD

**Issue by jiuribu** [Ipsis/Woot#123]
this thing happens , its hard to explain . connecting power before it complete cause same thing , area 3x3 just gone , fluids or anything else what is placed under it.

this is done in RF dimmension , very first one.

hermitapack 1.5.x is used with hell alot of mods removed (ic2 and semi alike)

https://youtu.be/n1VKbP2PYEs

made a video

this happened to me at 100% rate so this "bug" can be redone by same steps

rank 3 building is constructed , used "template" blue cube to show pattern.

used : woot-1.10.2-1.2.1.jar

**Comment by Ipsis** [comment]
This is ....... intentional and unfortunate.
The reason is that you built the factory too low in the world, but it is not your fault.

I had to make a workaround for mob drop learning, when mods were dropping loot in the world, rather than using an event mechanism. I basically created a 3x3 area at bedrock level where the loot could spawn and I could learn it safely. Once the learning phase is completed, this stops happening.

However this means that is you built the factory at bedrock, or near-bedrock then you would have this problem.

I completely forgot to tell people in the wiki page or in-game "manual", no to build too low.

I can only apologise,
I could never come up with a nicer solution. (see https://github.com/Ipsis/Woot/issues/90)

I'll add a note to the docs for this.
I think you are unfortunately the first person to come across this.
