### ISSUE TITLE
Duping Glitch

### ISSUE THREAD

**Issue by 2000game** [Ipsis/Woot#146]
https://vid.me/Fq7Z

take any mob who hasnt a loot table

**Comment by Ipsis** [comment]
Shhh, nobody is supposed to know about that :)

Basically that hole in the ground is to get around some mods dropping items in the world directly when a mob is killed, rather than letting Forge spawn them. While the factory is learning it kills a fake mob at bedrock and any bad-mods drop their loot down there, which I hoover up to learn. (That is why the manual says don't build the factory below Y=10)

If all mods played nice and just let Forge handle it, then everything would be fine, but that is of course up to the mod author.

One option may be to encase the learning area in bedrock to stop anyone from easily adding items.

**Comment by 2000game** [comment]
Or you say that no item coud get inside oder outside of that area

**Comment by Ipsis** [comment]
I just use a standard function from Forge that gets me all the entities within a certain area. I don't think there is a simple way of identifying entities dropped by a player rather than genuine loot drops - though I could be wrong.

**Comment by 2000game** [comment]
I mean that there is an invsible boarder at the end of the 3x3x1 room that no item could get in the room or out of the room

**Comment by 2000game** [comment]
Is there a command to stop the learning progress manually?

**Comment by Ipsis** [comment]
No, without the learning the mod wood never generate anything.

**Comment by 2000game** [comment]
the Problem is i build an Chaos Guardian Spawner and that spawns a lot of dragon hearts directly in my inventory and i would like to say to him that he has learned enough abbout it :D

**Comment by Ipsis** [comment]
By default 500 mobs, one every 20 ticks.
That can be changed in the configuration file.
The more mobs spawned the more accurate the loot percentages.

**Comment by 2000game** [comment]
Another option would be that the learning works in an extra dimension so that nobody could get there who isn't allowed.

**Comment by Ipsis** [comment]
That was a consideration earlier on ...... I was a bit reluctant to create a dimension as I think it would be a bit of an overhead.

**Comment by KendirkRS** [comment]
sorry to chime in could you talk with tema about using the Extrautils2 quarry dimension for it?

**Comment by ktole1999** [comment]
but then that mod would have to be installed to use the dimension, otherwise its back to creating your own or using an alternate method.

**Comment by KendirkRS** [comment]
Of cause did think of that just thought most mod packs with woot will have eu2

**Comment by Ipsis** [comment]
This is now being addressed. So I'm going with a box in the sky to handle this, which will be surrounded by barriers. The box will only exist when required and will then be removed. Hopefully this should stop this exploit. (Still not the best solution but I'm hoping it is better than before!)
