### ISSUE TITLE
[Request] Make colors more distinguishable for Color-blind players

### ISSUE THREAD

**Issue by UkeFox** [Ipsis/Woot#189]
Hey, Just a minor request;

I'm red-green colorblind. When using the Factory Layout block it is rather difficult for me to differentiate between the colored factory blocks, especially with red/gray/green varieties. 

If the ghost blocks were more opaque and a solid color with more saturation I'd have no trouble building the factories without having to guess the correct colors.  

Thanks.

**Comment by Ipsis** [comment]
Apologies, I didn't appreciate that this would be an issue. I'll modify the rendering code to try and make them render more clearly.

**Comment by UkeFox** [comment]
No worries! 

lol I was sitting there staring at the layout going, "Can't tell if gray or red.
Ended up calling my buddy over for help. 

BTW, thanks for the quick response. :)

**Comment by Ipsis** [comment]
I've bumped the opaque settings up so that they are less ghost-like but you can still tell when you have a real physical block placed.

The first is the old version, the second the new.
I can see a difference, but I'm not sure how far that goes to help you.

![old](https://cloud.githubusercontent.com/assets/5602759/25062686/b8583294-21c8-11e7-99fd-f70da82bff97.png)
![new](https://cloud.githubusercontent.com/assets/5602759/25062688/bb819668-21c8-11e7-89fa-502a9a25a7da.png)

**Comment by Ipsis** [comment]
This is now in 1.10.2-1.4.0.
Hopefully it will help you in some way.
Unfortunately I was not able to increase the saturation, but I did make the block as opaque as I could
