### ISSUE TITLE
[1.11.2] Random Ticking Entity Crash

### ISSUE THREAD

**Issue by Silvrus** [Ipsis/Woot#219]
Not sure what is causing this, but I'm getting a CTD with this error: https://pastebin.com/tvgm10Dv

Using Deadly Monsters and ESM, not sure if they're conflicting somehow. This is in a new world, don't even have a base setup yet.

Forge 13.20.0.2296
Woot 1.11.2-0.2.0

**Comment by Ipsis** [comment]
I changed over to identifying entities a bit differently in the latest release, in order to use the new internal naming that MC uses. I think there is something different with one of those mods and I'm not handling the failed lookups. I'll put some protection in to make this safer and see what is different with those two mods.

**Comment by Ipsis** [comment]
Although I can protect against this crash, which I will, it looks like Deadly Monsters is not registering its entities correctly in 1.11.2, which causes a null to be returned on lookup. 
https://github.com/bigbang87/deadly-monsters/issues/4

That bug links to the AbyssalCraft bug where the registration problem in Deadly Monsters was mentioned.

**Comment by Silvrus** [comment]
Awesome, thanks for looking into this, and getting it fixed. Woot is a big mod for my pack since you'll need mob drops but normal mob farms are going to prohibitively dangerous due to ESM.
