### ISSUE TITLE
[1.12] Question about whats left to do

### ISSUE THREAD

**Issue by Morpheus1101** [Ipsis/Woot#234]
I was looking at this mod for the MMD-Dev Server (https://github.com/MinecraftModDevelopment/MMD-Dev-Server) and at present it runs and loads a world on SP but as yet dosent load on SMP.  So i was curious to see how much more work is left to do before an Alpha//Beta build ?

**Comment by Ipsis** [comment]
1.12 basics are sort of done but I'm still playing with ideas as it is a complete rewrite. 
I'm probably going to release a basic alpha first with basic upgrades and limited configuration. 
This might happen in a few weeks... Hopefully.

**Comment by Morpheus1101** [comment]
Noone is running the mod, i was looking at the mod i'd compiled myself locally on my computer from what is here on git to see what stage things are

**Comment by Morpheus1101** [comment]
Now this works on Server and Client, i was looking to test out on my local computer and although the guide sais to use the mob prism, i dont actually see that in the list of bocks as yet, unless it has changed to something else or still to be implamented.

(Suggestion) With the new GuideBook(if not finished) have tabs for headings that suers can goto directly without having to scroll through the entire book again, even though technically they shouldnt need to

**Comment by Ipsis** [comment]
I've basically changed a lot of stuff and the prism is now gone. You now use an Ender Shard instead.
The GuideBook is getting thrown away and I'm going to add a new one based on the Guide-API.

The current 1.12 branch is still in an volatile state.
I'm trying to get the basics nailed down so that it will be in a playable state, just taking a bit longer than I though :(

**Comment by Fundryi** [comment]
Can't wait to see your mod it's so good for Servers, My server is dying because of the "Vanilla" Mob farms. 
:( Hope everything works out for you and we see a 1.12.1 Version anytime "soon" ;)

**Comment by RealGrep** [comment]
Hope this comes out soon. Other than being wonderful, generally, there's a huge hole in spawners for 1.12.x right now. No EnderIO powered spawner, or really anything to do that job. Closest is Soul Shards: The Old Ways, and that is approximately the opposite of this mod when it comes to being server friendly. lol

**Comment by Daihok41** [comment]
Yes i can not wait till this hits 1.12. Hoping it will be soon.

**Comment by Ipsis** [comment]
So just a quick update.
I've been cleaning up the mod to release an alpha.
This will very much be - here is an alpha of the mod, please give feedback and it will crash.
I will be discouraging people from putting it in modpacks that are public, mainly because it is very early code.

There is a project "https://github.com/Ipsis/Woot/projects/7" that shows which bits I still have to finish before the first alpha.

**Comment by Ipsis** [comment]
Alpha 0.0.1 for 1.12.2 is up on CurseForge awaiting approval by Curse.
