### ISSUE TITLE
[1.12.2] Ender Dragon drops infinite Dragon Hearts & Draconium Dust

### ISSUE THREAD

**Issue by wamc2017** [Ipsis/Woot#257]
Hi there,

I enjoyed playing your mod in 1.10 and now I moved to 1.12 and still like it so far, but I found a bug, which spawns infinite Dragon Hearts & Draconium Dust (every two seconds), if the player stands nearby the factory controller which is programmed for the Ender Dragon.

I haven't changed the default configs of Draconic Evolution or Woot.

Here you can find the modlist: https://pastebin.com/3vvqCJ8S

Draconic Evolution version: Draconic-Evolution-1.12-2.3.5.269
Woot version: woot-1.12.2-0.0.2

I compiled Avaritia and CodeChickenLib myself to test them out (maybe that has something todo with this problem?)

Thanks for looking into it. If you need anything else (logs or config files), please let me know. :)

Best regards
wamc

**Comment by Ipsis** [comment]
Now that is impressive. I added the Draconic support but it was untested, so clearly that was a mistake :) 

I'll replicate and get that fixed up in the next release.

**Comment by Ipsis** [comment]
Looks like instead of using just my hardcoded value for the EnderDragon, I'm actually killing them and trying to learn the loot. By doing so the Draconic items drop. EnderDragons dont die in the normal way, so Woot is not supposed to learn that way, but use fixed values instead.  So I've got a nasty bug :(
Time to fix!
