### ISSUE TITLE
[1.10.2] Woot not giving dragon scales for ArmorPlus

### ISSUE THREAD

**Issue by Byakuun** [Ipsis/Woot#281]
I have edited the config file the same way the tutorial for drak-evo was done and still cant get them on the drop table.

**Comment by Ipsis** [comment]
Can you let me see the lines that you added to woot.cfg to add your extra items.
That will make it a lot easier to replicate the issue.

**Comment by Byakuun** [comment]
Config: 
https://pastebin.com/PQz4h3wm

**Comment by Ipsis** [comment]
I think I know what is wrong and it shows up better with syntax highlighting in the dev environment
Your first line has a . instead of a , which is a really subtle difference to see.

        NO_ENCHANT,armorplus:ender_dragon_scale,1.20.0

You probably have a message in your logs that read:
[Woot]: Invalid dragon drop  - key,item,meta,stacksize,chance: NO_ENCHANT,armorplus:ender_dragon_scale,1.20.0

That basically stops the rest of the config section from parsing.

(Lines from your config)
        NO_ENCHANT,armorplus:ender_dragon_scale,1.20.0
        LOOTING_I,armorplus:ender_dragon_scale,1,40.0
        LOOTING_II,armorplus:ender_dragon_scale,1,60.0
        LOOTING_III,armorplus:ender_dragon_scale,1,80.0
Should be
        NO_ENCHANT,armorplus:ender_dragon_scale,1,20.0
        LOOTING_I,armorplus:ender_dragon_scale,1,40.0
        LOOTING_II,armorplus:ender_dragon_scale,1,60.0
        LOOTING_III,armorplus:ender_dragon_scale,1,80.0
