### ISSUE TITLE
woot not working at all on 1.12,2

### ISSUE THREAD

**Issue by ivangamerBr** [Ipsis/Woot#284]
i've tried everything and my friend also did and we cant have it to work at all

**Comment by Ipsis** [comment]
I need a bit more information as to what happens.
Is the mod running and you don't know how to get started or do you have a farm and it is not forming etc?
Did you install GuideAPI as you need that mod to get the ingame docs.

**Comment by ivangamerBr** [comment]
well the multiblock is not forming at all we tested everything/ prism is also not getting mobs dna

**Comment by Ipsis** [comment]
The multiblock will not form until you put a programmed controller on top.
You also need the power cell, importer and exporter blocks in place.

To get the programmed controller:
You need to hit a mob with the ender shard, then kill the mob.
Then use the programmed ender shard in the anvil to create the controller.

**Comment by EnigmaticValor** [comment]
I got a mob farm tier IV working (wither boss) but now it spawns drops (rib of wither from tiny progressions) like crazy around the structure but no nether stars. I cannot connect itemducts (TE) to exporter or importer either. Placing chests adjacent to blocks also does not seem to work
Edit: Got a zombie farm working (it exports now), still don't know how to import soul sand and wither skulls into the structure.

**Comment by Ipsis** [comment]
So there are a few things here:
- WitherBoss - Tiny Progressions I've not tested with. It must spawn extra items in world when I'm learning the drops. That will stop after a few minutes.  I'll need to look into that one. I intend to put a "loot learning dimension" into a newer release to handle these non-standard mods.

- The factory has no inventory which is why you cannot connect itemducts.
- A chest needs to be adjacent to the export so that the drops can be placed in it.
- A chest beside the importer is where you place the soul sand and wither skulls.
- The Wither wont spawn any items until you have the correct ingredients.

**Comment by Ipsis** [comment]
Loot learning dimension has been added so the Tiny Progressions loot drops wont litter the main area anymore.

**Comment by Solverbolt** [comment]
Woot farm as of Sky Adventures 1.4.0 using Minecraft 1.12.2 Does not form. Used even the little builder tool, added the final pieces that are not placed, including the exporter, importer and power cell. Still wont form. its sitting in its own chunk
![2019-03-10_17 46 42](https://user-images.githubusercontent.com/38087746/54094231-a113ea80-435c-11e9-888e-7bbfd3e04f60.png)
As mentioned before, there is an issue within your mod that is making it unplayable. had to use admin privileges to just get the Factory Base pieces, because it would not craft. Same with shards
