### ISSUE TITLE
Upgrade Recipes & Anvil Enchanted books

### ISSUE THREAD

**Issue by Mohron** [Ipsis/Woot#286]
forge-1.12.2-14.23.1.2560-universal
woot-1.12.2-0.0.4

![image](https://user-images.githubusercontent.com/3623122/34323263-8f6fde68-e806-11e7-8146-f0dad2d8e267.png)

The Recipes for the Woot upgrades won't take enchanted books made with OB's Auto Anvil due to their repair cost data. A freshly spawned in enchant book does work and does not have the Repair Cost property.

**Comment by Ipsis** [comment]
I use the Json recipe format where I have to specify the nbt data.
I don't think there is any way of handling these OB extended nbt books.

**Comment by Mohron** [comment]
I'm guessing the repair data is an over-generic handling issue on their part then? Because Using an anvil on anything else definitely add a repair cost prop. I didn't try combining the books in a normal anvil after I found the issue was the book's NBT tag.

**Comment by Ipsis** [comment]
I've not taken apart the tags yet, but a vanilla anvil does seem to go generate 2 nbt tags when combining books, where a cheated book only has one.

I'll see if there is any other way of handling the books in the recipes. I've yet to find anyone else using the json technique with enchanted books and the built-in processing. It looks like it only handles exact NBT matching which is a shame.

However because it probably breaks using the vanilla anvil, I'll mark as a bug and see if I can find a solution.

**Comment by Ipsis** [comment]
After asking for some pointers on the Forge forums I think I have something working.
So far I've got it working with both "pure" enchanted books and anvil produced books.
More testing required, but looking hopeful.

**Comment by Ipsis** [comment]
I've ran some testing and it looks like this fix will allow both anvil and enchantment table books to match. As long as only one enchant is on the book at it is the correct one it should work in the recipe.

The only catch is that if you setup AE2 autocrafting with the recipes for the non-anvil ones, then it wont use the anvil ones. You can still manually craft however, it is just autocrafting.

**Comment by Ipsis** [comment]
Need to update the recipes to use registry enchantment name rather than id, as these are allocated in a registry - Choonster via Forge forums
