### ISSUE TITLE
Factories not forming

### ISSUE THREAD

**Issue by jdk789** [Ipsis/Woot#291]
Hi,

I am having an issue where my factory will never form. I'm trying at first to create a teir 1 factory and i have everything as per the guide. also have the power, importer and exporter. I right click the factory block with a torch and it sais "validating" so everything is there. I am using a programmed controller for a PIG but it forever stays in validating status and doesnt ever form..

Regards
Jay_K

**Comment by JoeSGT** [comment]
read this it may help or not
https://github.com/Ipsis/Woot/issues/290

**Comment by JoeSGT** [comment]
There a new video just got push out by one of my friends here
https://www.youtube.com/watch?v=A128l2lc9Ws&feature=youtu.be

**Comment by Ipsis** [comment]
@JoeSGT  you get a cookie for the YouTube video. Plus I never knew you could apply power to the factory heart! I always attach the power input to the power cell block itself, since it is neater :)

@jdk789 Can you post an image of your factory please as I've created a pig tier 1 and it all forms - that is with a cheated in controller (using /woot give) and killing a pig in-game.
Out of interest how did you get the programmed controller?
