### ISSUE TITLE
Air Blocks in Drop?

### ISSUE THREAD

**Issue by jkroepke** [Ipsis/Woot#307]
See: https://i.imgur.com/vN7d3gs.png

Woot Version: 0.0.6

**Comment by Ipsis** [comment]
That happened to me while debugging something else so I  tracked it down and fixed it. I cannot however remember what piece of code I fixed.
I'll try and find the fix to see what the reason was.

Could you check if air is in your loot.json file or even better upload your loot.json file to paste in or the like and I can load it into my device area. 

 I think this is a gui issue rather something that would ever be generated by the farm as I don't recall it ever happening with the Top display.

**Comment by jkroepke** [comment]
All Fine.  Upgrade to latest version remove the air block from the drop list.

**Comment by Ipsis** [comment]
Excellent, that is what I was hoping.
If the bug does come back just reopen the bug and I'll investigate. 
There is always a chance Ive missed a corner case.
