### ISSUE TITLE
Add layer stepping to the guide block

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Woot#308]
On sneak activate of the guide block, step through the different layers of the current tier.
Changing tiers will reset the layers to all.

**Comment by calloatti** [comment]
This would be great.

The first time I tried to build a Tier IV, I just ended up going to creative and letting the guide block build it for me, since it was almost impossible to build by hand.

Maybe you could make the "ghost" blocks more transparent also?

Another thing: some blocks are too similar, only differing in some green/red pixels. Some people, me included have some degree of color blindness, and the red/green variant is the most common one.

http://www.color-blindness.com/red-green-color-blindness/

> More than 99% of all color blind people are suffering from a red-green color vision deficiency.
> 
> About 8% of all men and 0.5% of all women are suffering from it.

**Comment by Ipsis** [comment]
There is a config option that will turn all the block textures off and replace them with block colors with the layout guide
If you look in the config file and turn it on that might help. (simpleLayout=true)
I still need to have some sort of indication of color->block but it might help you out in the short term.
