### ISSUE TITLE
No information about what each tier allows

### ISSUE THREAD

**Issue by Annoyed1** [Ipsis/Woot#311]
So I'm sorry if this info is somewhere else but I've tried for hours to find which tier factory certain mobs require. I find it ridiculous that this isn't easy to find info on your wiki as this seems like extremely important information to have when trying to plan projects within my group since I'd have no idea what tier I would need for the mobs I want.

Like I said, sorry if this info is somewhere else however I've poured over this wiki and was very annoyed to not see this info. Is it really that difficult to provide? You coded it in after all.....

**Comment by Ipsis** [comment]
The reason it is not on the Wiki it because it is not pre-defined.
The tier required is calculated based on the health of the mob, although people can override this in the configuration.
When you create the mob controller for a specific mob, then the tooltip of that controller is updated to show the required tier.

![2018-02-03_08 12 17](https://user-images.githubusercontent.com/5602759/35765372-340a9976-08ba-11e8-81f8-4ef22659a91e.png)
