### ISSUE TITLE
loot

### ISSUE THREAD

**Issue by demon57730** [Ipsis/Woot#340]
hello i have a question maybe it's a problem
that's why woot does not make the file with all the default mobs and loot that are on the server

I explain the file just create the loot of the dragon but not that of the spider or squellette and all these other mob (have no mob blacklist nor whitlist)

what is problematic these means that I have to make the file mob by mob which and very long I would like to know if he has not a way to create all recipes low mob loot in 1 command or a way easy

_____________________________________________________________________________________________________

forge-1.12.2-14.23.2.2634-universal.jar

woot-1.12.2-1.0.1.jar

**Comment by Ipsis** [comment]
There is no need for a "loot" file for all the mobs since Woot learns the drops from the mobs as you create factories. The Dragon is a special case which is why you can see it in custom_drops.json.

You can see the loot that is learned by looking in the file woot/loot.json, which is in the same directory as the screenshots, save, world directories.

**Comment by demon57730** [comment]
well not at all I captured a skeleton and when I made the machine he had written well skeleton but he had no loot

**Comment by demon57730** [comment]
file woot/loot.json
{"version":1,"mobs":[],"drops":[]}

**Comment by demon57730** [comment]
solo it works i will try again on the server can be these a mod i have del who was the problem

another thing how to add the egg to the chicken

**Comment by demon57730** [comment]
For the loot these settle, I know where these came from. for the egg I'm going to look a little better the wiki thank you
