### ISSUE TITLE
Add BloodMagic crystal growth ritual

### ISSUE THREAD

**Issue by Ipsis** [Ipsis/Woot#349]
Add new ritual to allow the factory to produce different wills.
The quality of the will depends on the upgrade level.

Still not sure about the need of this, or the impact on Blood Magic.

**Comment by wamc2017** [comment]
Hmm, I would say, we don't need a will generation option (will itself isn't used in that many recipes), it would be better, if the Wootfarm could interact with the Gathering of the Forsaken Souls ritual (or some similar ritual) to accelerate the crystalgrowth.

The only problem I see here is, that the GotFS ritual works best if different mobs are killed, so it may be more attractive to do a traditional mobfarm instead of a woot one. (Which could maybe be solved if multiple mobs can be spawned by woot in one farm...)

An other option would be some kind of pedestial, where you could put a tartaric gem to fill it with will. (But don't know if this is too cheaty... :D)

**Comment by Ipsis** [comment]
People had asked for the farm to generate Wills, but I didn't know enough about Blood Magic to know how useful it was - so thankyou for clearing that part up.

I think that the tartaric gem filling was also mentioned a long time ago, but as you say that does seem a bit cheaty.

I'll take a look at the GotFS ritual to find out how it works and if Woot could interact in a useful way. My basic rule for mod support is that has to replace a possible, laggy mob far.. So if GotFS needs to kill mobs, then it could be a candidate.

**Comment by wamc2017** [comment]
Yeah GotFS acts the same as the Well of Suffering ritual, but instead of giving blood it accelerates will crystal growth above the ritual...

Using the wootfarm to fill a tartaric gem would make the demon crucible and the crystal farming kinda irrelevant, that's why I think it's a bad idea...

**Comment by Ipsis** [comment]
I've added my alternative to the GotFS - The Ritual Of The Cloned Soul - ie. no uniqueness.
Works in exactly the same way as GotFS in terms of crystal range, the only differences are the lack of uniqueness boost and the fact that it uses the factory as the source of the killed mobs.

**Comment by Ipsis** [comment]
c92d24c2c31c3eb1d87c69fad64f972769d6b912

Note to self - still needs a texture on the upgrade.
And I need to setup the ritual stones correctly.

**Comment by Nightcaste** [comment]
I'm just looking for clarification, the crystallizers need to be *above* this ritual, correct?

**Comment by Ipsis** [comment]
Sorry, I didn't see any notification on this bug, hence the slow response.
The ritual should work in the same was as the Gathering Of The Forsaken Souls, so I think they need to be above the master ritual stone.
