### ISSUE TITLE
No recipe for the Woot Guide

### ISSUE THREAD

**Issue by remclave** [Ipsis/Woot#384]
Mod Version 1.4.4
Forge Version 2760
Minecraft Version 1.12.2

A few weeks ago the recipe was in the mod. I am making a quest book and was double-checking my entries when I discovered that the Woot Guide no longer has a recipe.

**Comment by Ipsis** [comment]
The guide itself will not show up in JEI under @Woot as it is registered under the Guide API mod.
It should appear if you just search for Woot.

**Comment by remclave** [comment]
Thank you for your reply. However, I see the guide but when I click for a recipe, the recipe is no longer there. Is it possible that a setting to stop mobs from spawning in overworld would affect the recipe?

ETA: mobs can be spawned. they just are not allowed to spawn normally.

**Comment by Ipsis** [comment]
Mob spawning settings wont disable any recipes.
Could you give me a screenshot of the item you are clicking on.

**Comment by remclave** [comment]
Well, I checked the current update from the mod pack author and the issue appears to have resolved. The recipe is once again available. I do apologize for the inconvenience. I could still provide you with a screen shot if you want to see which "publication" I am viewing.

**Comment by Ipsis** [comment]
No problem.
If it is all working for you now, I'm more than happy with that.

**Comment by remclave** [comment]
The problem has resurfaced. Again, we're not certain which mod is interfering with the crafting of the Woot Guide. The Modpack on CurseForge is: Tactical Universe Presents Beyond The Void 2, version 4.7 using Woot version 1.4.6. 
![2018-10-29_10 55 06](https://user-images.githubusercontent.com/31051239/47662688-6a85c200-db69-11e8-96b2-6bb70f45a6da.png)

**Comment by Ipsis** [comment]
That is the correct book as it has the Guide-API textures. The old book was basically black and red.

Curse is failing to install that modpack so I cannot even check that.
Everything is registered via the Guide-API mod, rather than directly from Woot.  

Can you seach "@guide" and see if anything is registered for that mod and tell me which version of the Guide-API is installed in your instance.

**Comment by ghost** [comment]
We are using Guide-API-1.12.2-2.1.7-62 Beta version but we were also having trouble on the release version of Guide API. I can confirm this is also happening to other guides like Deep Mob Learning for example.

**Comment by Ipsis** [comment]
I've replicated this issue with your mod pack.
There were recipes for Blood Magic and Deep Mob Learning but not Woot.
However a simple Woot+Guide-API+JEI modpack exhibited no issues.

What I'll maybe do is drop a debug version of Woot in your modpack to see if the recipe register callback is made against my mod. That would at least indicate if the recipe is being added and then removed, or is never being registered in the first place.

It is completely possible that Woot is at fault here, however this is the only modpack that I've ever heard of this kind of issue.

**Comment by remclave** [comment]
Thank you for looking into it further! Because I have no skill set to determine the cause.

**Comment by Ipsis** [comment]
So I think that the issue is because of the Deep Mob Learning and Woot.
A minimal of DML/Guide-API/JEI/Woot causes the same problem.
On one boot the recipe will be there for DML but not Woot. On another boot Woot but not DML.

I'm still doing some debugging, but it looks like when the recipes are registered, whichever recipe Guide-API loads last between DML and Woot overwrites the other one.

eg.
BloodMagic gets added as guideapi:bloodmagic_guide
DML gets added as guideapi:guide
Woot gets added as guideapi:guide

So both DML and Woot are registering with setRegistryName("guide") and that breaks everything.

BloodMagic used to register under the same name but fixed it in April to go from guide->bloodmagic_guide.

The answer is therefore that Guide-API books should not use "setRegistryName("guide")" but should use a unique name. eg ("<mod_id>_guide")

DML:
`return new ShapelessOreRecipe(new ResourceLocation(DeepConstants.MODID, "guide"), bookStack, new ItemStack(Items.BOOK), new ItemStack(Registry.sootedRedstone)).setRegistryName("guide");`

Woot:
`return new ShapelessOreRecipe(new ResourceLocation(DeepConstants.MODID, "guide"), bookStack, new ItemStack(Items.BOOK), new ItemStack(Registry.sootedRedstone)).setRegistryName("guide");`

BloodMagic
`return new ShapelessOreRecipe(new ResourceLocation(BloodMagic.MODID, "guide"), GuideAPI.getStackFromBook(GUIDE_BOOK), new ItemStack(Items.BOOK), "blockGlass", "feather").setRegistryName("bloodmagic_guide");`

As a quick test, I updated my code to register as woot_guide and both recipes now appear. I'll have to load a test mod into your modpack first to confirm this of course.

**Comment by Ipsis** [comment]
I've tested the update mod with your modpack and can now see both recipes.
I've also uploaded to Curse so you should see 1.12.2-1.4.7 available when they process it.

**Comment by Ipsis** [comment]
@TacticalUniverse @remclave 
With the updates that DeepMobLearning and I have pushed out, can I take it that your issue is now solved?
