### ISSUE TITLE
Give Command

### ISSUE THREAD

**Issue by NatheArrun** [Ipsis/Woot#392]
In woot 1.12, "/woot give" universally returns (you do not have permission to use this command), despite being the OP of a SMP world. Is there a way to set the permissions of a player so that he/she can use the command?

**Comment by Ipsis** [comment]
I've had people mention this to me a few times.
In my dev environment and my test Curse profiles it all works fine when I'm OP, however there does seem to be an issue in some modpacks. eg. I have this issue in StoneBlock

The /woot command is registered at the same level as gamemode, give, tp etc.

Are you running a modpack at the moment?
Can you run the vanilla gamemode, give, tp commands without issue?

After looking at the code it is possible that I've got the commands registered at level 4 instead of 2, which is not what I expected. I'll investigate  a bit further, but if you change the server.properties and set the op-permission-level to 4 it might allow you to run those command.

**Comment by Ipsis** [comment]
I've investigated a bit more and it does look like
/woot - needs permission level 2
/woot give - needs permission level 4

So I have a bug in the mod that I need to fix, to move all the Woot subcommands down to level 2, which is what I originally intended.

I should be releasing 1.4.6 this weekend which will include this fix.

**Comment by NatheArrun** [comment]
Right then. Thanks for the hard work!

**Comment by Ipsis** [comment]
Fixed (hopefully) in 1.12.2-1.4.6.
