### ISSUE TITLE
Changing the power per tick needed to a lower value makes the factory want to consume more?

### ISSUE THREAD

**Issue by TheRealDadbeard** [Ipsis/Woot#393]
Okay first my config file here: https://hastebin.com/ozatahezen.bash

So I wanted it more energy efficient but now it seems I need to give it more power to fill up the biggest power cell?

Any ideas what's going on?

**Comment by Ipsis** [comment]
Just so I'm clear on the changes you've made:

deathXp=1->3
spawnTicks=320->240
t1PowerTick=80->60
t2PowerTick=160->120
t3PowerTick=240->200
t3PowerTick=320->280
Changes in the upgrades for their PowerTick values

So effectively you have made the "cost per tick" values lower, which should decrease the overall cost to spawn. The reduction in the spawnTicks value will however bump your "cost per tick" up since the factory is running faster and if you use rate upgrades that will increase further.

My guess is that by dropping the "spawnTicks" you've pushed up the "cost per tick" even though the overall cost to spawn is reduced.

Can you drop your "spawnTicks" change back to 320 and see if it behaves more as you expect.
