### ISSUE TITLE
[1.10.2 - Question] Setting spawn time for specific mob

### ISSUE THREAD

**Issue by Steve505** [Ipsis/Woot#395]
Hey there!
I was just wondering, if we can on our modded server increase spawn cooldown for Wither Boss, as we don't want to make Mob Factory "too OP".

Thanks.

**Comment by Ipsis** [comment]
Unfortunately the mob specific configuration was only introduced in the 1.12 version of the mod, specifically for reason as this. The older versions of the mod only allowed a global spawn time.
The only thing you could really do would be to up the RF cost for that mob to make it more expensive, but it would still spawn in the same time (globalSpawnCostList).

Granted it has been a while since I looked at the 1.10.2 codebase, but I think that is a restriction.
