### ISSUE TITLE
Wither Boss drains power even with no supplies

### ISSUE THREAD

**Issue by raindropworks** [Ipsis/Woot#399]
Looked at #260 to see what details you worked off of with Wither Boss generation, not sure if it's a bug per se or not, but If you make a Wither Boss generator and feed it the 4 soul sand and 3 wither skulls, it runs and generates the loot, as expected.  But if there aren't enough supplies, the generator still runs.  No loot is dropped, but power is still consumed.

I mention this because I have circuits on my farms feeding redstone to the controller based on if the output chest is full or not as a way to save power.  I -can- just add a lever to that farm to manually turn it off when it's not in use, but it's a step away from the full automation I was hoping for.

Either way is fine, and it's not a huge deal, just wanted to know if this was as designed or not

**Comment by Ipsis** [comment]
Short answer: as designed :)

Long answer:
To check that the items exist every tick is quite expensive. Not impossible, but I felt that it was too much of an overhead.
So Woot basically consumes all the power it needs, then at the point of generating the loot will check the inventories/tanks for whatever ingredients are needed. If they are there, you get the loot, otherwise you get nothing.

Hope that helps.

**Comment by raindropworks** [comment]
In hindsight, makes perfect sense, thank you!
