### ISSUE TITLE
Ore dictionary chest in recipes

### ISSUE THREAD

**Issue by LemADEC** [Ipsis/Woot#401]
As of 1.12.2-1.4.8, recipes are forcing vanilla chest, preventing integration with other mods.
Consider using 'chest' or 'chestWood' ore dictionary entries instead to support other mods.

**Comment by Ipsis** [comment]
The recipes haven't been changed and have always used "minecraft:chest" as the ingredient.
Are you saying that this used to work for you before and now it doesn't, or am I just reading to much into "As of 1.12.2-1.4.8"?

I can certainly look at moving to ore dictionary for the chests.

**Comment by LemADEC** [comment]
1.12.2-1.4.8 is your mod's version where I see the issue. I didn't test previous versions, but I bet the issue is there for a long time.

**Comment by LemADEC** [comment]
On a side note, consider adding ore dictionary registration for Stygian iron ingot and plates, respectively ingotStygianIron and plateStygianIron. This will give other mods a chance to integrate with plate production.

**Comment by Ipsis** [comment]
I've added the ore dictionary chest recipe.
However I'm not going to add the ingots and plates to the ore dictionary, simple because they are used in both vanilla and anvil crafting. Anvil crafting has no ore dictionary support.

But any other mod should be able to produce real stygian iron plates via any mechanism they wish without requiring the ore dictionary. I'm not sure that they require ore dict entries to work.

**Comment by LemADEC** [comment]
Adding those ore dictionary entries allows mods to parse through the registry and automatically add recipes for machines to produce plates.
I understand the anvil doesn't support Stygian plates or ingots added by other mods, which is fine.

**Comment by Ipsis** [comment]
Fixed in 1.4.9
