### ISSUE TITLE
[Suggestion] Config option to disable mod compat

### ISSUE THREAD

**Issue by GamertechAU** [Ipsis/Woot#407]
Essentially, I'd like config options for Woot so blocks and compatibility for mods Woot works with such as EvilCraft and BloodMagic can be disabled and their respective blocks removed and unregistered, similar to the existing xp shards option.

Currently Woot attempts to load all blocks including those that require materials from mods that aren't installed, generating loading errors as well as showing the unused blocks in JEI. eg

[Client thread/ERROR] [FML]: Parsing error loading recipe woot:upgrade_bm_crystal_i
com.google.gson.JsonSyntaxException: Unknown item 'bloodmagic:demon_crystallizer'

Ideally, Woot would check the config, identify mod compats that are disabled and not attempt to register blocks for those mods. This would clean up JEI a little for players as well as optimise pack loading the slightest fraction. (I'm a perfectionist ¯\_(ツ)_/¯  ) 

Thanks Ipsis

**Comment by Ipsis** [comment]
Can I take it that the options in the config don't work quite as you want as they only stop the recipe being added, but still allow the blocks to be displayed in JEI?

factorymoduspport {
    # Pass the IMC recipe additions to EnderIO
    B:EnderIOIMC=true

    # Allow the factory to support BloodMagic Ritual Of The Cloned Soul
    B:allowBmCrystal=true

    # Allow the factory to support BloodMagic Ritual Of The Mechanical Altar
    B:allowBmLeAltar=true

    # Allow the factory to support BloodMagic Ritual Of The Sanguine Urn
    B:allowBmLeTank=true

    # Allow the factory to support EvilCraft Blood Generation
    B:allowEcBlood=true
}

**Comment by GamertechAU** [comment]
Correct. I have EvilCraft in the pack, but not BloodMagic.

While I've disabled the 3 BM entries you've posted there's no option to disable creation of the recipes for the BM blood collection blocks, just support of the rituals.

Woot generates errors in the logs as it attempts to create the recipes and still shows the BM blocks in JEI.

**Comment by Ipsis** [comment]
I've had a quick check of the options.
allowBmCrystal=false fails to remove the Crystal I/II/III upgrade recipes
allowBmLeAltar=false correctly removes the Life Essence Altar I/II/III upgrade recipes
allowBmLeTank=false correctly removes the Life Essence Tank I/II/III upgrade recipes

So there is definitely a bug with the allowBmCrystal config option - mainly because I forgot to hook the code up for that one. So I'll get that fixed up and it should remove the errors in the logs.

The blocks themselves will still show up in JEI, they just wont be craftable.

**Comment by GamertechAU** [comment]
That'll work. Thanks Ipsis :)

**Comment by Ipsis** [comment]
Fixed in next release 1.12.2-1.4.10
