### ISSUE TITLE
Woot farms not Forming in Sky Adventures 1.4

### ISSUE THREAD

**Issue by Solverbolt** [Ipsis/Woot#408]
Minecraft Version 1.12.2
FTB Sky Adventures 1.4

they dont form. Also shards and other pieces are not crafting on the anvil

Not really sure how you would repeat it unless you load up that modpack

Had to admin create particular items in order to even try to build the woot farm

![image](https://user-images.githubusercontent.com/38087746/54173888-f9bcb380-4440-11e9-8dcc-25b2d2794e7b.png)

**Comment by Ipsis** [comment]
I've loaded up Sky Adventures 1.4 and created a Tier I factory with no issues.
Similarly I've created different shards on the anvil without issue.

So for you factory, do you have the exporter/importer/cell situated below the factory?
What mob is programmed into the controller block?
If you change the Hammer mode to validate the tier of factory you have build and then right-click on the factor heart, what does it tell you?
Do you have any other mods installed into the pack aside from the standard ones that come with Sky Adventures 1.4?

**Comment by Solverbolt** [comment]
No other mods besides what came with sky adventures, and I was trying to setup a wither farm, so I have the exporter and importers underneath, directly below the premium power cell. the wand tells me nothing, as I have it setup with the exact materials it calls for when its set to tier 4

**Comment by Ipsis** [comment]
I've just created a formed Tier IV farm for the Wither so that confirms that the mob isn't blacklisted. I've also checked the FTB configs and nothing looks out of place.
When I validate using the hammer  (Mode Validate Tier IV) I get the following messages

"
Validating factory for IV
Found Power Cell at ..
Found Importer at ..
Found Exporter at ..
Found valid Tier IV factory
"

Validating with a missing block gives me a message to indicate "expected X found air "

However, looking at the picture you provided - do you have the controller on the top of the heart block?
If so then the factory wont form, it needs to be on the block behind the heart. If you put the layout block down somewhere it will show you were the controller goes. The images in the guide can be a touch deceiving - however the validate part of the hammer should tell you about the missing controller.

In the original woot (pre 1.12) the controller did go on the heart, but it was moved in 1.12 to give better access.
