### ISSUE TITLE
Blood Magic Tank Upgrades

### ISSUE THREAD

**Issue by Alexis-Grimm** [Ipsis/Woot#413]
So i know you've had a lot of issues related to blood magic, but I don't think i've found this issue. I'm using version 1.0.0 of ftb sky odyssey. When i fully upgrade a zombie based woot farm with blood magic life essence tank upgrades (tier 3) and hold shift on the factory heart, it reads 80 sacrifice runes, now when building an altar which only has 80 sacrifice runes and nothing else i generate over 4000 lp for one zombie that i kill, however the woot farm produces only a measly 85 life essence from one zombie kill. I understand that it produces somewhere around 500 lp every 4 seconds with full rate and mass upgrades but this is still a long way from 4000 per mob. I would think this is either a bug itself, or just a typo. (Also as a side note the well of suffering in this situation produces nearly 300 lp per damage done to a single mob, with 80 runes of sacrifice.)

**Comment by Ipsis** [comment]
I think it is a display bug, as I get the same "80 runes" for each of the Blood Magic LE Tank upgrades.
It should be - according to the config - 
Tier 1 upgrade - 4
Tier 2 upgrade - 16
Tier 3 upgrade - 24

The 80 is actually the power per tick cost of the upgrade and I was calling that instead of the rune count for display in the GUI. 

So the correct rune count is being used, it is just the display in the GUI is wrong.
It will be fixed in the next release of Woot.

**Comment by Ipsis** [comment]
Fixed in 1.12.2-1.4.11
