### ISSUE TITLE
[1.9.4] Better Debugging of Errors

### ISSUE THREAD

**Issue by tommyTT** [Ipsis/Woot#42]
I would like to suggest adding some sort of way to see why the multi block isn't forming. I wanted to test something in a test world and created a new pack for it, but the multi block doesn't form and I have no idea why. I rebuilt every way I could think of and nothing happens. In my current main pack I have no problems with it forming. So, it would be nice to see, where the problem actually is. The first time I used it in my survival world I wasn't aware that the next tier requires changes to the previous tier (I think that should also be changed), but I had no idea because the layout block didn't really indicate anything of that sort. A simple message in chat "Block at x,y,z is invalid", like big reactors did it (and blood magic will do it soon), would be very helpful.

**Comment by Ipsis** [comment]
The reason that the next tier doesn't build on a full previous tier is mainly to do with the way that the multiblock is formed. I need to avoid the case where the factory spans more than one chunk and it ends up parsing a full lower tier factory when you haven't chunkloaded the whole area.

I'll see if I can find some way of validation having some feedback. The multiblock works off events rather then checking the structure on every tick, so I will probably have some way to interact with the factory and get a "block x,y,z is invalid" type message.

The multiblock will also not form if you try to program a higher tier mob into a lower tier factory. However I may not give any useful feedback in that situation other than a failure to form the multiblock.

**Comment by tommyTT** [comment]
That sounds good. I feel, the required tier for a mob should somehow be in the tooltip of the prism or the configured controller. However, that isn't the problem in my test world. I used a tier 1 factory with a zombie and a cow, it didn't work. I tried it in a tier 3 factory and it also didn't form. I have no idea what I'm doing wrong and will wait until the next version, maybe something in my test pack is screwed up.

**Comment by Ipsis** [comment]
So for the next release this will happen.
When you right-click on the factory block, if it is formed, then you will get the Waila/TOP style information as currently happens.
If is not formed, then it will force a validation of the factory and tell you what error stopped it from continuing the validation. It cannot tell you all the errors, just the current one.

It will tell you:

* if the mob controller is missing
* if there is no mob in the controller
* incorrect block type at a position
* if the mob xp requirement is too much for the current tier

Because it doesn't know which tier you are building it will report the error on each tier that the factory size could allow.

**Comment by tommyTT** [comment]
Sounds very good. Thanks, I'm looking forward to testing it.

**Comment by tommyTT** [comment]
So, I figured out the problem I had yesterday with the factory not forming. I updated to the newest version 0.2.0-beta but it wouldn't work and the error log didn't report a problem either. I started a new test world and there I had no problem. I tried a few things and found out, that the problem occurs when the gamerule doDaylightCycle is false. I thought I would let you know, maybe there is some sort of way around that. 

Another thing you might consider is extending the /woot command so I can set the type for the prism in creative (and peaceful) without having to spawn in the mob itself, since there are no spawn eggs for some mobs (e.g. wither skelly or the wither).

On to the thing I wanted to test in the first place ...

**Comment by Ipsis** [comment]
Sorry, I never saw this update since the bug was in the closed list. I'll create a new bug and investigate. The doDaylightCycle should not change anything but I'm happy to be proven wrong.

I'll also raise an another bug for the woot command extension. I normally use spawn eggs or build the wither manually and then swap back to peaceful when I'm testing, but it would be a nice easy fix for that. I'll see what I can do.
