### ISSUE TITLE
Can we add mobs?

### ISSUE THREAD

**Issue by Spontini** [Ipsis/Woot#425]
Hello, is there a way to add mobs into the WOOT mod? For example i want to add animated blocks from Erebus into WOOT, is there a config for it?

**Comment by Ipsis** [comment]
Woot automatically works with all mobs, however there I some that I need to blacklist due to the way that the mob dies or the drops it creates.
I've unfortunately had to internally blacklist erebus:erebus.animated_block as it was identified as causing issues when working with Woot. Please see https://github.com/Ipsis/Woot/issues/358 for the explanation.
