### ISSUE TITLE
1.15.2 Server crash

### ISSUE THREAD

**Issue by Jergeric** [Ipsis/Woot#440]
Aloha, unfortunately we had some crashes yesterday, so we had 
to remove Woot :/ It usually happens when logging in or less minutes later

If further logs are required, please contact us
[crash-2020-07-27_23.00.45-server.txt](https://github.com/Ipsis/Woot/files/4986635/crash-2020-07-27_23.00.45-server.txt)

If I have misinterpreted the logs and it has a different origin, I apologize.

**Comment by Ipsis** [comment]
So it looks like something is being killed by an arrow. When it dies an event is raised and Woot is registered to see and process that event. 
I then take the entity that died and get its entity key from Minecraft (eg. minecraft:cow). For some reason this particular entity doesn't have a valid entity key so getEntityString returns null and I then process it, causing the crash.

I'm not sure what particular entity is being killed, only that it is a MonsterEntity.
I'd love to know what entity is being killed by an arrow, but there is no way of knowing from that debug.

I'll need to put some extra protection into my code, so that when this situation occurs (getEntityString returning null for the entity) then I don't try to process it.

Probably push a new version of Woot this weekend with that protection in, which should hopefully solve the issue for you.

**Comment by Jergeric** [comment]
Many thanks for the answer and your quick reaction^^
Unfortunately I can't say anything specific about the situation, because there is a traditional monster farm in this area 😅🙄

**Comment by Ipsis** [comment]
This is hopefully fixed in 1.15.2-1.1.1.1, but I'll leave the bug open for now.
Up on CurseForge - just waiting for approval.
