### ISSUE TITLE
Cancel simulation?

### ISSUE THREAD

**Issue by The-Tarkol** [Ipsis/Woot#443]
I didn't see an option in the commands to cancel a simulation, but I'd like to be able to cancel one (or all) simulations for times when a "bad" mob is simulated. Checking TPS, Tartarus is running at a nice 4.396, which is a bit crippling for everyone else. Just wanting to cancel the simulation and I'll make a loot table for the mob being simulated.

**Comment by Ipsis** [comment]
Do you know which particular mob is being simulated?
I know that some do things like spawn other mobs on death, and I normally blacklist those, however since we are early in 1.15, I've not had a chance to identify these incompatible mobs.

If you still want to allow the mob, but not simulate, then there is an option in the config "customDropsOnly" which is supposed to avoid simulation for problematic mobs and allow you to provide a custom drops file. 

Custom drop files normally work in addition to the simulated drops, but with "customDropsOnly" it becomes the only source of drop information for that mob.

**Comment by The-Tarkol** [comment]
As it turns out, one of the ops on the server tried to manually "simulate" it numerous times. It was a rat, from the "rats" mod. Once the simulations finished, we had no further issues :)
