### ISSUE TITLE
[Suggestion] Industrial Foregoing Support

### ISSUE THREAD

**Issue by SomewhatDamaged** [Ipsis/Woot#462]
Put simply, a way to produce Industrial Foregoing pink slime, liquid meat, and/or essence from mobs being farmed.

It would be a great feature that would save server owners having to put up with ungainly, 25x25 mob farms of memory eating.

Probably the easiest way to add them would be to have a liquid output block that uses either a Mob Crusher (items + essence) or a Mob Slaughter Factory (pink slime + liquid meat).

**Comment by Ipsis** [comment]
I added this to earlier versions of Woot where there was custom handling for pink slime but had held off for now as Industrial Foregoing hadn't implemented it yet for 1.15/1.16.

If that is now in their mod, then I'll look at added support for pink slime as a start.

For the liquid meat and essence I already have exporter blocks that can output items or fluid so I'd probably just reuse those. I'll require a new perk to output those liquids - which can be crafted from the blocks you suggest. The only real issue is going to be calculating amount of liquid meat/essence for a specific mob, but I'll need to look into that.

**Comment by SomewhatDamaged** [comment]
> I added this to earlier versions of Woot where there was custom handling for pink slime but had held off for now as Industrial Foregoing hadn't implemented it yet for 1.15/1.16.

[Yeah, they have a Release version out for 1.16.4.](https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing/files/all?filter-game-version=1738749986%3a70886)

**Comment by Ipsis** [comment]
Current plans for this support:

- Perk A - mob slaughter - follows I/F mechanics
  - Recipe for the perk will use the Mob Slaughter block
  - Liquid Meat
    - Animal will generate health mb
    - Non-animal will generate health * 20 mb
  - Pink Slime
    - Animal will generate health * 20 mb
    - Non-animal will generate health mb
  - Different levels of Perk A will generate 100%/120%/140% of the above liquids
  - Perk A percentages will be configurable


- Perk B - mob crushers - follows I/F mechanics
  - Recipe for the perk will use the Mob Crusher block
  - Generates essence based off mob xp
  - Different levels of Perk B will generate 100%/120%/140% of the liquid
  - Perk B percentages will be configurable

Both perks will output to tanks adjacent to any side of the factory exporter block.
Perk A will require two tanks.
Perk B will require one tank.

**Comment by Ipsis** [comment]
https://github.com/Ipsis/Woot/commit/5170e13642e88a359f6ddf4f6cfb28d468965e9a

Support added and it will be present in the next release of Woot.
