### ISSUE TITLE
Magus plate wont craft in injections press.

### ISSUE THREAD

**Issue by lookwow** [Ipsis/Woot#469]
Trying to create magus plates in injection press. I input plate and diamond and have 5k enchant and power, but it wont craft. Just sits there. Playing ATM6 mod pack.

**Comment by Ipsis** [comment]
The magus plate is quite slow as it takes ~75 seconds @ 20 RF/tick, so any visual progress in the bar will take a while to register, although from your report it sounds like you have already left it for a while.

There is a known issue with the injection press where you must have the exact ingredients for some of the recipes as the stack count of the second ingredient was failing on recipe lookups when more than the correct amount was required. That is going to be fixed in the next release. https://github.com/Ipsis/Woot/issues/451
