### ISSUE TITLE
Strange item eating bug (1.16.4: DW20 pack)

### ISSUE THREAD

**Issue by KirbyQK** [Ipsis/Woot#490]
Had this very strange issue that started when I tried to move my setup from one area to another in my base.

After placing the layout and heart, placing the perk slot would cause it to disappear, along with anything that you subsequently like onto that space. Then it seemed to do it with any block I placed adjacent until I built across to it, which fixed it in general.

Videos of the issue:

https://youtu.be/diHPpjxTbXA
https://youtu.be/9c7X-j5Xo54

**Comment by Ipsis** [comment]
I think I know what this is - but I thought I had fixed it in recent releases.
I wasn't handling the placement of blocks against a heart correctly since it was the only block with a gui as well.
I'm wondering if I fixed the layout/guide block issue but not the heart one.

You should be find if you place the block against a lower block, but placing against the heart looks like it is broken.

Need to dig out the fix I did for the layout and apply it to the heart.

Thanks for the video link, that made it a lot clearer to understand.

**Comment by KirbyQK** [comment]
Awesome! I replicated it again today upgrading to tier 2 - put a cobble frame around the heart and was able to build it no problems :) Thanks!

**Comment by Ipsis** [comment]
Fixed in 1.16.4-1.0.3.1
