### ISSUE TITLE
exoctics seem too rare

### ISSUE THREAD

**Issue by DA3monking** [Ipsis/Woot#492]
at 1% for a single block, at a 1/12 for certain blocks, means checking about 1200 chests for a specific block, assuming your world prefers the 2 loot rooms with 2 chest cities(mine does not) that means 300 cities, which is rarer than seems necessary

**Comment by Ipsis** [comment]
The drop rates are standard loot tables so they can be changed using standard vanilla datapacks.
I will look at increasing them to be a bit more generous - my main concern was them being powerful but easily found - however with the numbers you presented it does seem to be pitched a bit low.

Currently there is a 1% drop chance, with weights of 4/4/2/1/1 for the different exotics.
I'll bump that up to a 15% drop chance, but keep the weights the same - that should be a bit more generous but still leave them as 'rare'.

**Comment by cainamar** [comment]
to provide an example: I teleported around using the locate command and found two ARN and one PAZ out of a couple hundred thousand blocks in each direction

I would agree that might be a bit rare but I've also ended up with a nearly self-sustaining pair of magister tier farms spitting out loot insanely fast because of the PAZ, so I'd also agree that keeping them rather rare is a good call

**Comment by Ipsis** [comment]
I've had a couple of other nudges about the drop rate, so -
Bumped from 1% to 15%

This should still make it rare to find an exotic, but you have a greater chance of getting a non-OP one (hopefully).

Updated in 1.16.4-1.0.3.1
