### ISSUE TITLE
[1.10.2] Config option for whitelisting mobs

### ISSUE THREAD

**Issue by tommyTT** [Ipsis/Woot#65]
I'm using the mod again in my custom modpack that is running on 1.10.2 and so far no problems. However, I had an idea how to integrate your mod into the pack by preventing the default mechanic to obtain the prism by hitting the mob and instead I want it to be crafted (with a Tier 5 shard from Soul Shard The Old Way). To achieve this I found the blacklist option that is only used when hitting the mob, not when it gets spawned in a factory, but maybe I'm wrong about that? Regardless, I now have to blacklist all entities which is a bit of work, especially when other mods add new ones. So it would be very helpful if I could switch it to whitelist instead? 

Thanks for your work!

**Comment by Ipsis** [comment]
No you are right, the blacklist only works when capturing.
So just out of interest, what is the output of your crafting recipe .... just a unprogrammed  prism?

It shouldn't be too difficult for me to add a whitelist option to the prism capture mechanics, plus another option to select whitelist or blacklist.

My only problem just now is time.
I've got an overhaul of the mob learning mechanics ready to go (which it saves across games) plus a better progression through the tiers. I'm also struggling to decide on 1.9.4 support, rather than just doing 1.10! (I'll probably just add new features to 1.10 and not 1.9.4).

So I'll add the support, but it probably wont be available until the next 1.10 release of the mod, which will hopefully be soon.

**Comment by tommyTT** [comment]
The crafting recipe will be something like "Some sort of higher tier material from another mod plus a tier 5 soul shard for a mob will give you the programmed prism for that mob". For the moment I found all the mobs for my current pack, so I'm good, but for future uses in other packs I think this would save people a lot of time. So no rush, finish the more important things first, I'm interested to see what comes up next.

If it was me, I would drop the 1.9.4 support since I see no reason for people not to update to 1.10. But it is not my decision and you must do what is best for you.

**Comment by tommyTT** [comment]
I'm using Crafting Harmonics and use a recipe that looks something like this:

`{
                    "type": "addShaped",
                    "output": {
                        "item": "woot:prism:0",
                        "nbt": "{mobName:\"Woot:none:Zombie\",displayName:\"Zombie\",mobXpCost:5}"
                    },
                    "with": [
                        "botania:elfGlassPane:0", "botania:elfGlassPane:0", "botania:elfGlassPane:0",
                        "botania:elfGlassPane:0", {
                            "item": "soulshardstow:ItemSoulShard:0",
                            "nbt": "{Entity:\"Zombie\",Tier:5,KillCount:1024}",
                            "fuzzyNbt": true,
                            "returnOnCraft": true
                        }, "botania:elfGlassPane:0",
                        "botania:elfGlassPane:0", "botania:elfGlassPane:0", "botania:elfGlassPane:0"
                    ]
                }`

It is not pretty, so because of the current functionality of Crafting Harmonics I must probably add an identical recipe for every mob type, but it works for the moment.

**Comment by Ipsis** [comment]
I'd never heard of the mod before, but that explains how you can set the nbt values.

**Comment by tommyTT** [comment]
Yes it is nice but still a bit limited, I think I need to also look at the Minetweaker clone again, but that one gave me a lot of troubles the last time I tried it.
