### ISSUE TITLE
Mob Factory spawns item drops

### ISSUE THREAD

**Issue by feldim2425** [Ipsis/Woot#90]
I found out that ActuallyAdditions and RFToolsDimension still spawn drops in the world (tested with enderman). 

It think if the in the priority in the event handler is the lowest the setCanceled(true); will not effect event handler with normal priority.

**Comment by Ipsis** [comment]
Can you tell me which version of the mod you are using, as I had added a sneaky fix to hopefully handle that and at what Y level your factory is at. The fix was in 1.10.2-0.2.5-alpha

I register with the lowest priority as I want all possible mods to add their mob drops before I look at the loot. 

There are mods that in the LivingDropsEvent will spawn items in world and not add them to the event drop list for Forge to spawn. I believe that ActuallyAdditions and RFTools both do that. Of course there is nothing wrong with them doing that.

So I thought I had fixed this, but of course I could be wrong.

**Comment by Ipsis** [comment]
I've loaded up my latest release with RFToolsDimentions and ActuallyAdditions. I can see the RFToolsDimension drops appearing, so I'll look into that. I'm not seeing AA drops. Which of those drops did you see?

**Comment by Ipsis** [comment]
I think I know what is going on. To learn the mob drops, I spawn a mob at Y=1, fakeplayer kill it then process the drop events and try and pickup any of these other drops that are spawning.

I think the loot is spawning inside a block and that is causing it to be accelerate upwards. I can replicate it by changing the position that I spawn the mob at and that changes the velocity.

Need to think of some way to workaround that.

**Comment by Ipsis** [comment]
64fc998d810a83ffc2fc8ce809246bfe28731287
